// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: video.proto

package video

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VideoService_VideoProccess_FullMethodName = "/VideoService/VideoProccess"
)

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoServiceClient interface {
	VideoProccess(ctx context.Context, opts ...grpc.CallOption) (VideoService_VideoProccessClient, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) VideoProccess(ctx context.Context, opts ...grpc.CallOption) (VideoService_VideoProccessClient, error) {
	stream, err := c.cc.NewStream(ctx, &VideoService_ServiceDesc.Streams[0], VideoService_VideoProccess_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &videoServiceVideoProccessClient{stream}
	return x, nil
}

type VideoService_VideoProccessClient interface {
	Send(*Video) error
	Recv() (*CommonResponseVideo, error)
	grpc.ClientStream
}

type videoServiceVideoProccessClient struct {
	grpc.ClientStream
}

func (x *videoServiceVideoProccessClient) Send(m *Video) error {
	return x.ClientStream.SendMsg(m)
}

func (x *videoServiceVideoProccessClient) Recv() (*CommonResponseVideo, error) {
	m := new(CommonResponseVideo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility
type VideoServiceServer interface {
	VideoProccess(VideoService_VideoProccessServer) error
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVideoServiceServer struct {
}

func (UnimplementedVideoServiceServer) VideoProccess(VideoService_VideoProccessServer) error {
	return status.Errorf(codes.Unimplemented, "method VideoProccess not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	s.RegisterService(&VideoService_ServiceDesc, srv)
}

func _VideoService_VideoProccess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoServiceServer).VideoProccess(&videoServiceVideoProccessServer{stream})
}

type VideoService_VideoProccessServer interface {
	Send(*CommonResponseVideo) error
	Recv() (*Video, error)
	grpc.ServerStream
}

type videoServiceVideoProccessServer struct {
	grpc.ServerStream
}

func (x *videoServiceVideoProccessServer) Send(m *CommonResponseVideo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *videoServiceVideoProccessServer) Recv() (*Video, error) {
	m := new(Video)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VideoService_ServiceDesc is the grpc.ServiceDesc for VideoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VideoProccess",
			Handler:       _VideoService_VideoProccess_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "video.proto",
}
